In [1]:
import torch
from torch.utils.data import DataLoader

# Dummy data
data = torch.tensor([[1.0, 2.0], [2.0, 4.0], [3.0, 6.0], [4.0, 8.0]])
targets = torch.tensor([[3.0], [6.0], [9.0], [12.0]])

# Buat DataLoader
dataset = torch.utils.data.TensorDataset(data, targets)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

# Definisikan model Anda dan optimizer (contoh sederhana)
model = torch.nn.Linear(2, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# Definisikan Mean Squared Error (MSE) loss
loss_fn = torch.nn.MSELoss()

# Training loop
for epoch in range(5):
    for batch_data, batch_targets in dataloader:
        print(batch_data, batch_targets)
        print("+-----------------------------------+")
        # Reset gradients
        optimizer.zero_grad()

        # Forward pass
        predictions = model(batch_data)

        # Hitung loss
        loss = loss_fn(predictions, batch_targets)

        # Backward pass
        loss.backward()

        # Update weights
        optimizer.step()

    print(f"Epoch {epoch+1}, Loss: {loss.item()}")

tensor([[4., 8.],
        [3., 6.]]) tensor([[12.],
        [ 9.]])
+-----------------------------------+
tensor([[1., 2.],
        [2., 4.]]) tensor([[3.],
        [6.]])
+-----------------------------------+
Epoch 1, Loss: 2.411588430404663
tensor([[1., 2.],
        [4., 8.]]) tensor([[ 3.],
        [12.]])
+-----------------------------------+
tensor([[3., 6.],
        [2., 4.]]) tensor([[9.],
        [6.]])
+-----------------------------------+
Epoch 2, Loss: 0.06810042262077332
tensor([[3., 6.],
        [1., 2.]]) tensor([[9.],
        [3.]])
+-----------------------------------+
tensor([[4., 8.],
        [2., 4.]]) tensor([[12.],
        [ 6.]])
+-----------------------------------+
Epoch 3, Loss: 0.0017325824592262506
tensor([[4., 8.],
        [1., 2.]]) tensor([[12.],
        [ 3.]])
+-----------------------------------+
tensor([[3., 6.],
        [2., 4.]]) tensor([[9.],
        [6.]])
+-----------------------------------+
Epoch 4, Loss: 0.0013137826463207603
tensor([[1., 2.],


In [2]:
import torch
from torch.utils.data import DataLoader

# Dummy data
data = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0])
targets = torch.tensor([2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0, 20.0])

# Split data into sequences
sequence_length = 3
sequences = []
next_targets = []
for i in range(len(data) - sequence_length):
    sequences.append(data[i:i+sequence_length])
    next_targets.append(targets[i+sequence_length])

# Convert to tensors
sequences = torch.stack(sequences)
next_targets = torch.stack(next_targets)

# Create Dataset and DataLoader
dataset = torch.utils.data.TensorDataset(sequences, next_targets)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

# Define your model and optimizer (example simple model)
model = torch.nn.Linear(sequence_length, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# Define Mean Squared Error (MSE) loss
loss_fn = torch.nn.MSELoss()

# Training loop
for epoch in range(5):
    for batch_sequences, batch_next_targets in dataloader:
        print(batch_sequences, batch_next_targets)
        print("+------------------------------+")
        # Reset gradients
        optimizer.zero_grad()

        # Forward pass
        predictions = model(batch_sequences)

        # Calculate loss
        loss = loss_fn(predictions.squeeze(), batch_next_targets)

        # Backward pass
        loss.backward()

        # Update weights
        optimizer.step()

    print(f"Epoch {epoch+1}, Loss: {loss.item()}")



tensor([[6., 7., 8.],
        [2., 3., 4.]]) tensor([18., 10.])
+------------------------------+
tensor([[4., 5., 6.],
        [1., 2., 3.]]) tensor([14.,  8.])
+------------------------------+
tensor([[7., 8., 9.],
        [3., 4., 5.]]) tensor([20., 12.])
+------------------------------+
tensor([[5., 6., 7.]]) tensor([16.])
+------------------------------+
Epoch 1, Loss: 23.2703914642334
tensor([[1., 2., 3.],
        [4., 5., 6.]]) tensor([ 8., 14.])
+------------------------------+
tensor([[7., 8., 9.],
        [5., 6., 7.]]) tensor([20., 16.])
+------------------------------+
tensor([[6., 7., 8.],
        [3., 4., 5.]]) tensor([18., 12.])
+------------------------------+
tensor([[2., 3., 4.]]) tensor([10.])
+------------------------------+
Epoch 2, Loss: 2.0164029598236084
tensor([[5., 6., 7.],
        [2., 3., 4.]]) tensor([16., 10.])
+------------------------------+
tensor([[6., 7., 8.],
        [7., 8., 9.]]) tensor([18., 20.])
+------------------------------+
tensor([[4., 5., 6

/Users/pabrik/working/mekarsa/products/economics/analyzer/venv/lib/python3.10/site-packages/torch/nn/modules/loss.py:536: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [3]:
data.shape, targets.shape

(torch.Size([10]), torch.Size([10]))

In [4]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader

# Definisikan dataset Anda
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self, data):
        self.data = data
    
    def __getitem__(self, index):
        return self.data[index]
    
    def __len__(self):
        return len(self.data)

# Contoh data (dapat diganti dengan data Anda sendiri)
data = torch.randn(100, 1)
targets = torch.randn(100, 1)

# Inisialisasi DataLoader
dataset = CustomDataset(list(zip(data, targets)))
dataloader = DataLoader(dataset, batch_size=10, shuffle=True)

# Inisialisasi model dan loss function
model = nn.Linear(1, 1)
criterion = nn.MSELoss()

# Loop melalui setiap batch dalam DataLoader
for batch in dataloader:
    inputs, targets = batch
    
    # Reset gradien
    model.zero_grad()
    
    # Hitung output model
    outputs = model(inputs)
    
    # Hitung loss
    loss = criterion(outputs, targets)
    
    # Backpropagation
    loss.backward()
    
    # Update parameter model
    optimizer.step()
    
    # Tampilkan loss
    print("MSE Loss: ", loss.item())


MSE Loss:  0.9044798016548157
MSE Loss:  1.6105905771255493
MSE Loss:  1.1529138088226318
MSE Loss:  1.3033933639526367
MSE Loss:  0.749358057975769
MSE Loss:  2.405273199081421
MSE Loss:  3.8140811920166016
MSE Loss:  0.8594918251037598
MSE Loss:  2.856786012649536
MSE Loss:  0.8489143252372742


In [5]:
dataset.data

[(tensor([-1.4207]), tensor([-0.5652])),
 (tensor([-0.9099]), tensor([0.1320])),
 (tensor([1.3217]), tensor([-0.0725])),
 (tensor([-1.1514]), tensor([-0.2268])),
 (tensor([-0.1645]), tensor([1.2981])),
 (tensor([-0.7324]), tensor([-0.6122])),
 (tensor([0.9532]), tensor([0.0832])),
 (tensor([0.0025]), tensor([-1.1895])),
 (tensor([-0.0892]), tensor([1.0167])),
 (tensor([0.2030]), tensor([0.5355])),
 (tensor([-0.7983]), tensor([-0.3132])),
 (tensor([-0.8797]), tensor([-0.2771])),
 (tensor([-0.7805]), tensor([-0.4865])),
 (tensor([-1.7532]), tensor([1.5360])),
 (tensor([0.6920]), tensor([-0.4155])),
 (tensor([-1.0876]), tensor([-1.0180])),
 (tensor([-0.6236]), tensor([-0.7386])),
 (tensor([-0.9927]), tensor([-0.1602])),
 (tensor([-0.4787]), tensor([0.1146])),
 (tensor([1.1122]), tensor([-2.1933])),
 (tensor([1.2549]), tensor([1.3161])),
 (tensor([-0.9870]), tensor([-1.8248])),
 (tensor([0.5345]), tensor([1.6953])),
 (tensor([-0.5064]), tensor([-0.5439])),
 (tensor([-0.0323]), tensor([0.45

In [6]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

# Definisikan dataset Anda
class CustomDataset(Dataset):
    def __init__(self, data, window_size):
        self.data = data
        self.window_size = window_size
    
    def __getitem__(self, index):
        window = self.data[index:index+self.window_size]
        target = self.data[index+self.window_size]
        return window, target
    
    def __len__(self):
        return len(self.data) - self.window_size

# Contoh data (dapat diganti dengan data Anda sendiri)
data = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Inisialisasi DataLoader dengan window_size = 3
dataset = CustomDataset(data, window_size=3)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

# Loop melalui setiap batch dalam DataLoader
for batch in dataloader:
    windows, targets = batch
    
    # Reset gradien
    model.zero_grad()
    
    # Flatten windows menjadi batched input
    inputs = windows.view(len(windows), -1)
    
    # Hitung output model
    outputs = model(inputs)
    
    # Hitung loss
    loss = criterion(outputs, targets)
    
    # Backpropagation
    loss.backward()
    
    # Update parameter model
    optimizer.step()
    
    # Tampilkan loss
    print("MSE Loss: ", loss.item())


RuntimeError: mat1 and mat2 must have the same dtype

In [7]:
inputs, targets

(tensor([[4, 5, 6],
         [5, 6, 7]]),
 tensor([7, 8]))